# Generated by Django 4.0.1 on 2022-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
