# Generated by Django 4.0.1 on 2022-08-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_user_gender_delete_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
