# Generated by Django 4.0.1 on 2022-08-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_migration',
            name='address',
        ),
    ]
