# Generated by Django 4.0.1 on 2022-08-10 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_application_migration_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Migration_Older',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('id_card', models.FileField(upload_to='documents/ID_cards/')),
                ('status', models.IntegerField(choices=[(0, 'Sent'), (1, 'Confirmed'), (2, 'Registred'), (3, 'Printed')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
