# Generated by Django 4.0.1 on 2022-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_user_age_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
