# Generated by Django 4.0.1 on 2022-08-10 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_application_migration_older'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_citizenship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application_migration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application_migration_older',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.blog'),
        ),
        migrations.AlterField(
            model_name='queue_citizenship',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.application_citizenship'),
        ),
        migrations.AlterField(
            model_name='queue_citizenship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='queue_migration',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.application_migration'),
        ),
        migrations.AlterField(
            model_name='queue_migration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply_comment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.comment'),
        ),
        migrations.AlterField(
            model_name='reply_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
