# Generated by Django 4.0.1 on 2022-08-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_application_citizenship_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
